FROM BASEIMAGE

# If we're building for another architecture than amd64, the CROSS_BUILD_ placeholder is removed so e.g. CROSS_BUILD_COPY turns into COPY
# If we're building normally, for amd64, CROSS_BUILD lines are removed
CROSS_BUILD_COPY qemu-QEMUARCH-static /usr/bin/

RUN apk add --no-cache gptfdisk util-linux coreutils
COPY rookd /usr/bin/
COPY ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["/usr/bin/rookd"]
